ignore:
  - "node_modules"
  - "dist"
  - ".git"

rules:
  # Rule 1: Architecture tracks core logic
  - doc: "docs/architecture.md"
    source: "packages/core/src/**/*.ts"

  # Rule 2: Configuration tracks the config definition
  - doc: "docs/configuration.md"
    source: "packages/core/src/config.ts"

  # Rule 3: README tracks the core detection logic and hashing algorithm
  # Rationale: If the core detection logic or hashing algorithm changes, the main documentation implies a change in behavior/features and should be flagged.
  - doc: "README.md"
    source: 
      - "packages/core/src/drift.ts"
      - "packages/core/src/analysis/hasher.ts"

git:
  ignoreCommitPatterns:
    - "^chore:"
    - "^style:"
    - "^ci:"

semantic:
  enabled: true
